name: flutter_path
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  flutter_animate: ^4.5.0
  toastification: ^1.2.1
  icons_plus: ^5.0.0
  google_fonts: ^6.2.1
  level_map: ^0.2.0
  game_level_map: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lotties/
    - assets/sounds/
